sensor:
  - platform: pulse_counter
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    internal_filter: 6us
    unit_of_measurement: "mm"
    name: 'Rainfall'
    accuracy_decimals: 3
    filters:
      - multiply: 0.2
      - debounce: 1s
    state_class: total_increasing


utility_meter:
  rain_daily:
    source: sensor.rainfall
    cycle: daily
  rain_weekly:
    source: sensor.rainfall
    cycle: weekly
  rain_monthly:
    source: sensor.rainfall
    cycle: monthly
  rain_yearly:
    source: sensor.rainfall
    cycle: yearly

type: entities
entities:
  - entity: sensor.rainfall
  - entity: sensor.rain_daily
  - entity: sensor.rain_weekly
  - entity: sensor.rain_monthly
  - entity: sensor.rain_yearly







# sensor:
#   - platform: pulse_counter
#     name: "Rain Guage"
#     pin: GPIO23
#     unit_of_measurement: 'mm'
#     filters:
#       - multiply: .02

#     total:
#       unit_of_measurement: 'mm'

# 3_______________________________________________

# sensor:
#   - platform: history_stats
#     name: "Rainsensor flips/h"
#     entity_id: binary_sensor.rain_gauge_rain_gauge_status
#     state: "on"
#     type: count
#     start: "{{ now() - timedelta(hours=1) }}"
#     end: "{{ now() }}"

# template:
#   - sensor:
#       - name: Rainfall [h]
#         state_class: total_increasing
#         unique_id: rainfall_h
#         unit_of_measurement: mm
#         icon: mdi:weather-pouring
#         state: >-
#           {% set count = states('sensor.rainsensor_flips_h') | int(0) %}
#           {% set mm = count * 0.631356 %}
#           {% if count >= 0 %}
#             {{ mm|round(1, 'floor') }}
#           {% endif %}

#         availability: "{{ (states('sensor.rainsensor_flips_h') not in 'unknown', 'unavailable')) }}"